### ISSUE TITLE
uninitialized constant GeminaboxRelease::Bundler

### ISSUE THREAD

**Issue by Jpuelpan** [dfherr/geminabox-release#6]
I'm using this gem and getting this error when running `rake inabox:release`.

```bash
juan@juan-mbp:mygem (master) [!] $ rake inabox:release --trace
rake aborted!
NameError: uninitialized constant GeminaboxRelease::Bundler
/Users/juan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/geminabox-release-0.2.0/lib/geminabox-release.rb:60:in `patch'
/Users/juan/projects/mygem/Rakefile:4:in `<top (required)>'
/Users/juan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/rake_module.rb:28:in `load'
/Users/juan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/rake_module.rb:28:in `load_rakefile'
/Users/juan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:689:in `raw_load_rakefile'
/Users/juan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:94:in `block in load_rakefile'
/Users/juan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/juan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:93:in `load_rakefile'
/Users/juan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:77:in `block in run'
/Users/juan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/juan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.2/lib/rake/application.rb:75:in `run'
/Users/juan/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rake-11.1.2/bin/rake:33:in `<top (required)>'
/Users/juan/.rbenv/versions/2.3.0/bin/rake:23:in `load'
/Users/juan/.rbenv/versions/2.3.0/bin/rake:23:in `<main>'
```

I think it's because `bundler` should be required in [geminabox-release.rb](https://github.com/dfherr/geminabox-release/blob/master/lib/geminabox-release.rb)

**Comment by dfherr** [comment]
tbh i'm not sure if thats some issue on your side that could be fixed otherwise.

requirering bundler doesnt seem such a big thing though, as it is assumed bundler is used anyway.

**Comment by Jpuelpan** [comment]
@dfherr Thanks for replying and sorry for my late response. You're right it's not necessary to require Bundler here. I'm closing this issue and PR.
